version: '3.3'
services:
  app:
    build: .
    # command: gunicorn main:app --bind 0.0.0.0:8000 -w 2 --reload --log-level "debug"
    command: gunicorn main:app --bind 0.0.0.0:8000 -w 2 --reload
    restart: aways
    expose:
      - 8000
    networks:
      - app-net
  
  nginx:
    build:
      context: ./nginx
    ports:
      - 1085:80
    networks:
      - app-net

networks:
  app-net: